version: '3'

services:
  web:
    build: .
    container_name: app
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
    
  db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - uri='mongodb://db:27017/test'
